apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-prime-clone
  labels:
    app: prime-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prime-clone
  template:
    metadata:
      labels:
        app: prime-clone
    spec:
      containers:
        - name: prime-clone
          image: mkhnoori1/amzprime
          ports:
            - containerPort: 80
          env:
            - name: VITE_APP_TMDB_V3_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tmdb-secret
                  key: tmdb-api-key
          resources:
            requests:
              memory: "256Mi"  # Minimum amount of memory to allocate
              cpu: "250m"      # Minimum CPU allocation
            limits:
              memory: "512Mi"  # Maximum memory the pod can use
              cpu: "500m"      # Maximum CPU the pod can use
